server.port: 8888

management.endpoints.web.exposure.include: "*"
management:
  endpoint:
    metrics.enabled: true
    prometheus.enabled: true
    routes.enabled: true
    health:
      show-details: ALWAYS

logging.level.org.springframework.security: DEBUG

eureka:
  client:
    enabled: false


spring:
  profiles:
    include: git
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/OlegNyr/config-proc.git
#          searchPaths: rib
          clone-on-start: true

        encrypt:
          enabled: true

key: test